
import java.sql.Connection;
import java.util.Scanner;
import java.util.Date;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * parkir.java
 *
 * created on Jul 27, 2021, 10:00:00 AM 
*/
/**
 *
 * @author Harry Kurniawan
 */
public class parkir extends javax.swing.JFrame {

    /**
     * Creates new form parkir
     */
    public parkir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        tombol_edit = new javax.swing.JButton();
        tombol_jammasuk = new javax.swing.JButton();
        tombol_jamkeluar = new javax.swing.JButton();
        tombol_delete = new javax.swing.JButton();
        Judul = new javax.swing.JLabel();
        nopolisi_label = new javax.swing.JLabel();
        jnskendaraan_label = new javax.swing.JLabel();
        biaya_label = new javax.swing.JLabel();
        rp_label = new javax.swing.JLabel();
        Tangga_Jam = new javax.swing.JTextField();
        pilihjnskendaraan = new javax.swing.JComboBox<>();
        nopolisi_isi = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tombol_edit.setBackground(new java.awt.Color(0, 0, 0));
        tombol_edit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tombol_edit.setText("Edit");
        tombol_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_editActionPerformed(evt);
            }
        });

        tombol_jammasuk.setBackground(new java.awt.Color(0, 0, 0));
        tombol_jammasuk.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tombol_jammasuk.setText("Jam Masuk");
        tombol_jammasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_jammasukActionPerformed(evt);
            }
        });

        tombol_jamkeluar.setBackground(new java.awt.Color(0, 0, 0));
        tombol_jamkeluar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tombol_jamkeluar.setText("Jam Keluar");
        tombol_jamkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_jamkeluarActionPerformed(evt);
            }
        });

        tombol_delete.setBackground(new java.awt.Color(51, 0, 51));
        tombol_delete.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tombol_delete.setText("Delete");
        tombol_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_deleteActionPerformed(evt);
            }
        });

        Judul.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Judul.setText("Sistem Parkir PT XYZ");

        nopolisi_label.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nopolisi_label.setText("No. Polisi");

        jnskendaraan_label.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jnskendaraan_label.setText("Jenis Kendaraan");

        biaya_label.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        biaya_label.setText("Biaya:");

        rp_label.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rp_label.setText("Rp.");

        Tangga_Jam.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Tangga_Jam.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Tangga_Jam.setText("Tanggal :\t\t\tJam :\t");
        Tangga_Jam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tangga_JamActionPerformed(evt);
            }
        });

        pilihjnskendaraan.setEditable(true);
        pilihjnskendaraan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Motor", "Mobil", "Truk" }));
        pilihjnskendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihjnskendaraanActionPerformed(evt);
            }
        });

        nopolisi_isi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nopolisi_isiActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jnskendaraan_label)
                    .addComponent(nopolisi_label))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pilihjnskendaraan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nopolisi_isi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(biaya_label)
                    .addComponent(rp_label))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Judul)
                .addGap(179, 179, 179))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(tombol_jammasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tombol_jamkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tombol_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tombol_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 85, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tangga_Jam)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Judul, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(Tangga_Jam, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nopolisi_label)
                    .addComponent(biaya_label)
                    .addComponent(nopolisi_isi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jnskendaraan_label)
                    .addComponent(rp_label)
                    .addComponent(pilihjnskendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tombol_jammasuk)
                    .addComponent(tombol_jamkeluar)
                    .addComponent(tombol_edit)
                    .addComponent(tombol_delete))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>                        

    private void tombol_editActionPerformed(java.awt.event.ActionEvent evt) {                                            
    Connection con = (Connection) new koneksi().getConnection();
    }                                           

    private void tombol_jammasukActionPerformed(java.awt.event.ActionEvent evt) {                                                
    System.out.print("Masukkan jam Masuk : ");
    int InHour = Integer.parseInt(sc.next());
    System.out.print("Masukkan menit Masuk : ");
    int InMinute = Integer.parseInt(sc.next());
    }                                               

    private void tombol_jamkeluarActionPerformed(java.awt.event.ActionEvent evt) {                                                 
    System.out.print("Masukkan jam keluar : ");
    int OutHour = Integer.parseInt(sc.next());
    System.out.print("Masukkan menit pulang : ");
    sint OutMinute = Integer.parseInt(sc.next());
    }                                                

    private void tombol_deleteActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void nopolisi_isiActionPerformed(java.awt.event.ActionEvent evt) {                                             
    System.out.println (“Masukan No Polisi”);
    String No_Polisi = input_masuk.next();
    }                                            

    private void Tangga_JamActionPerformed(java.awt.event.ActionEvent evt) {                                           
    java.util.Date;
    }                                          

    private void pilihjnskendaraanActionPerformed(java.awt.event.ActionEvent evt) {                                                  
    System.out.println("1. Motor");
    System.out.println("2. Mobil");
    System.out.println("3. Truk");
    }                                                 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        total_Jam_parkir = jam_keluar-jam_masuk;
        switch (tipe){
        case 1:
        tarif_Parkir = total_Jam_parkir * 2000;
        break;
        case 2:
        tarif_Parkir = total_Jam_parkir * 4000;
        break;
        case 3:
        tarif_Parkir = total_Jam_parkir * 5000;
        break;

        default:
        tarif_Parkir = 0;
        break;
        }
        
        System.out.println (“Biaya Parkir”);
        if (tipe == 1){
        System.out.println (” Jenis Kendaraan : Motor”);
        }else if (tipe == 2) {
        System.out.println (” Jenis Kendaraan : Mobil”);
        }else if (tipe == 3){
        System.out.println (” Jenis Kendaraan : Truk”);
        }else{
        System.out.println (” Jenis Kendaraan Tidak Terdaftar”);
        }
        
        System.out.println (” No_Polisi : ” + No_Polisi);
        System.out.println (” Jam Masuk : ” + jam_masuk+ “WIB”);
        System.out.println (” Jam Keluar : ” + jam_keluar+ “WIB”);
        System.out.println (” Lama Parkir : “+ total_Jam_parkir + “Jam”);
        System.out.println (” Tarif Parkir : Rp.” + tarif_Parkir);

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(parkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(parkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(parkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(parkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new parkir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel Judul;
    private javax.swing.JTextField Tangga_Jam;
    private javax.swing.JLabel biaya_label;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jnskendaraan_label;
    private javax.swing.JTextField nopolisi_isi;
    private javax.swing.JLabel nopolisi_label;
    private javax.swing.JComboBox<String> pilihjnskendaraan;
    private javax.swing.JLabel rp_label;
    private javax.swing.JButton tombol_delete;
    private javax.swing.JButton tombol_edit;
    private javax.swing.JButton tombol_jamkeluar;
    private javax.swing.JButton tombol_jammasuk;
    // End of variables declaration                   
}